version: "3.6"

services:
  php-cli:
    build:
      context: ./docker/php-cli
    volumes:
      - ./:/mnt/code
    working_dir: /mnt/code
    environment:

  php-fpm:
      build:
        context: ./docker/php-fpm
      volumes:
        - ./:/mnt/code:cached
        - ./docker/php-fpm/php-custom.ini:/usr/local/etc/php/conf.d/php-custom.ini
      working_dir: /mnt/code
  mysql:
    build:
      context: ./docker/mysql
    volumes:
      - ./docker/mysql/startup-scripts:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: database
    ports:
      - 3313:3306
  nginx:
      image: nginx:1.19.9
      container_name: nginx
      volumes:
        - ./docker/nginx/conf.d:/etc/nginx/conf.d
        - ./public/:/mnt/code/public:ro
      ports:
        - 808:80
